# 定时备份url远程文件 到GitHub仓库
# 给予GitHub仓库写入权限 https://github.com/dylanbai8/my_typecho_sqlite_backup/settings/actions
# 配置 FILE_URL 变量 https://github.com/dylanbai8/my_typecho_sqlite_backup/settings/secrets/actions
# 配置 HOOK_URL 变量 (用于推送成功通知)

name: 定时备份

on:
  schedule:
    - cron: '0 2 * * 1'  # 每周一凌晨 2 点
  workflow_dispatch:  # 支持手动触发

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: XXXXX 设置保存到仓库的路径 XXXXX
      run: |
        echo "DIRs_PATH='./typecho_sqlite/'" >> $GITHUB_ENV
        echo "FILE_PATH='./typecho_sqlite/back_up.db'" >> $GITHUB_ENV

    - name: 下载文件
      run: |
        curl -L -o downloaded_file $(echo ${{ secrets.FILE_URL }})

    - name: 创建目录并移动文件
      run: |
        mkdir -p ${{ env.DIRs_PATH }}
        mv downloaded_file ${{ env.FILE_PATH }}

    - name: 提交和推送文件
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 配置 Git 用户信息
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        # 提交更改
        git add ${{ env.FILE_PATH }}
        git commit -m "定时备份" --allow-empty
        git push

    - name: 推送成功通知
      run: |
        curl $(echo ${{ secrets.HOOK_URL }})
