name: File Sync

on:
  schedule:
    # 定时每周执行一次（星期一凌晨 2 点）
    - cron: '0 2 * * 1'
  workflow_dispatch: # 添加手动触发

jobs:
  sync-file:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 下载文件
    - name: Download file from URL
      run: |
        curl -L -o downloaded_file $(echo ${{ secrets.FILE_URL }})

    # 提交和推送文件
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 配置 Git 用户信息
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # 将文件保存到仓库根目录
        mv downloaded_file ./ # 如果需要指定文件名，可改为：mv downloaded_file ./new_filename
        
        # 提交更改
        git add downloaded_file
        git commit -m "Update file from URL (cron job or manual)"
        git push
